# Site settings
title: Cloudscaping
description: >
  A blog
baseurl: ""
url: "cloudscaping.co.uk"

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

# Includes an icon in the footer for each user name you enter
footer-links:
  github: bhummerstone
  twitter: bhummerstone