# Site settings
title: Cloudscaping
description: >
  A blog
baseurl: /
url: http://cloudscaping.co.uk
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

# About/contact
author:
  name: Ben Hummerstone
  github: bhummerstone
  twitter: bhummerstone